sudo: required

language: bash

services:
  - docker

env:
  - VAGRANT_VERSION=1.8.4

install:
  - wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
  - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb

script:
  - ./test/build.sh
  - ./test/check_version.sh
